---
- hosts: jenkins
  become: yes  
  tasks:
  - name: Upgrade packages
    yum:
      name: "*"
      state: latest
  - name: Install JDK 1.8
    yum:
      name: java-1.8.0
      state: latest
  - name: Remove JDK 1.7
    yum:
      name: java-1.7.0-openjdk
      state: absent